root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server/"
  bin = "tmp/main"
  full_bin = "PORT=3000 ./tmp/main"
  include_ext = ["go", "html", "css", "js"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  stop_on_error = true
  log = "air_errors.log"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  time = false